// @ts-expect-error - radix ui
import '@radix-ui/themes/styles.css';
// @ts-expect-error - global CSS side-effect import has no type declarations
import './globals.css';
// @ts-expect-error - theme config
import './theme-config.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import Navbar from '@/components/navbar';
import { Theme, ThemePanel } from '@radix-ui/themes';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={inter.variable}>
      <body className={`antialiased`}>
        <Theme accentColor='iris' grayColor='mauve'>
          <Navbar />
          <main className='px-4'>{children}</main>
          <ThemePanel />
        </Theme>
      </body>
    </html>
  );
}
